irqdomain: include linux/bug.h for WARN_ON()
Commit 6d274309d (irq: support domains with non-zero hwirq base)
introduced a WARN_ON() for an invalid hwirq in irq_domain_to_irq() but
doesn't include linux/bug.h resulting in:

include/linux/irqdomain.h: In function 'irq_domain_to_irq':
include/linux/irqdomain.h:78:2: error: implicit declaration of function 'WARN_ON'

if it isn't implicitly pulled in before.

Cc: Rob Herring <rob.herring@calxeda.com>
Cc: Grant Likely <grant.likely@secretlab.ca>
Cc: Thomas Gleixner <tglx@linutronix.de>
Signed-off-by: Jamie Iles <jamie@jamieiles.com>